### ISSUE TITLE
How to auto close the previous 'virtual-keyboard' upon opening a new one.

### ISSUE THREAD

**Issue by mjosephdelrosario** [the-darc/angular-virtual-keyboard#10]
I am having a problem of overlapping 'virtual-keyboard's when clicking multiple input-types without closing the previous ones -- how could i auto close it?

**Comment by the-darc** [comment]
It is a bug in the api. I would investigate it soon. Still, pull requests are welcome!

**Comment by mjosephdelrosario** [comment]
Great plugin port! Btw, for the issue above, i just used lodash and angular's jqlite for fixing it(within self.attachVki() function). But also looking for forward for the official fix.

``` javascript
    VKI_addListener(elem, 'click', function(e) {
      if (self.VKI_target == this) {
          e = e || event;
          if (e.stopPropagation) { e.stopPropagation(); } else e.cancelBubble = true;
          // For triggering close to non-focused virtual keyboard elements
          angular.forEach( angular.element(document).find('input'), function(value) {
              var inputChild = angular.element(value);
              if(_.isEqual('true', inputChild.attr('VKI_attached')) && !_.isEqual(elem, value)) {
                  inputChild.triggerHandler('close');
              }
          });
      }
      return false;
    }, false);
    if (self.VKI_isMoz)
      elem.addEventListener('blur', function() { this.setAttribute('_scrollTop', this.scrollTop); }, false);
    // Attach close event handler.
    angular.element(elem).bind('close', function(){ self.VKI_close(); });
    VKI_addListener(document.documentElement, 'click', function(e) { self.VKI_close(); }, false);
```

Added these:

```
          // For finding all input type elements with attached VKI
          angular.forEach( angular.element(document).find('input'), function(value) {
              var inputChild = angular.element(value);
              if(_.isEqual('true', inputChild.attr('VKI_attached')) && !_.isEqual(elem, value)) {
                  inputChild.triggerHandler('close');
              }
          });
```

```
           // For attaching a close event handler
           angular.element(elem).bind('close', function(){ self.VKI_close(); });
```

**Comment by pspk** [comment]
Thank you havocdrake!

I am using textarea widgets with the virtual keyboard - so I added one more angular.foreach to detach keyboards from the textarea widgets:

```
      angular.forEach( angular.element(document).find('textarea'), function(value) {
          var inputChild = angular.element(value);
          if(_.isEqual('true', inputChild.attr('VKI_attached')) && !_.isEqual(elem, value)) {
              inputChild.triggerHandler('close');
          }
      });
```

**Comment by mjosephdelrosario** [comment]
Note this is not the official fix -- But I am glad that those hack-fix could help :>

**Comment by luiscarlosjayk** [comment]
At [line 241](https://github.com/the-darc/angular-virtual-keyboard/blob/master/release/angular-virtual-keyboard.js#L241)

`VKI_addListener(document.documentElement, 'click', function(e) { self.VKI_close(); }, false);`

The close function is being called when clicked on blank space in the page. But not if clicked on another input or other elements that could take focus too e.g. `labels`.

**Comment by JinlingLi** [comment]
Add a listener for blur event as well?:
VKI_addListener(elem, 'blur', function(e) {
      if (self.VKI_target == this) {
        e = e || event;
        if (e.stopPropagation) { e.stopPropagation(); } else e.cancelBubble = true;
        // For triggering close to non-focused virtual keyboard elements
        angular.forEach( angular.element(document).find('input'), function(value) {
            var inputChild = angular.element(value);
            if(_.isEqual('true', inputChild.attr('VKI_attached')) && !_.isEqual(elem, value)) {
                inputChild.triggerHandler('close');
            }
        });
      } return false;
    }, false);

**Comment by the-darc** [comment]
solved in version 0.4.2

**Comment by luiscarlosjayk** [comment]
I downloaded version 0.4.2 and issue still happens. (using chrome)
and I also get an error: Uncaught RangeError: Maximum call stack size exceeded

**Comment by the-darc** [comment]
@Ciul, the [demo page](http://the-darc.github.io/angular-virtual-keyboard/) is using version 0.4.2 and testing it on my chrome (_v44.0.2403.125 (64-bit)_) the issue appears to be solved. Could you be more specific about where you found the _Maximum call stack_ error?
